import Head from 'next/head';
import Category from '../components/Category/Category';
import CourseInfo from '../components/CourseInfo/CourseInfo';
import Courses from '../components/Courses/Courses';
import Footer from '../components/Footer/Footer';
import Hero from '../components/Hero/Hero';
import JoinWorkShop from '../components/JoinWorkShop/JoinWorkShop';
import Navbar from '../components/Navbar/Navbar';
import Testimonial from '../components/Testimonial/Testimonial';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen">
        <Hero />
        <div className=" space-y-8 lg:space-y-14">
          <Category />
          <Courses />
          <JoinWorkShop />
          <CourseInfo />
          <Testimonial />
          <Footer />
        </div>
      </main>
    </>
  );
}
